### PR TITLE
function name idlePacket not capitalized in one place

### PR DESCRIPTION
**Pull request by dwightkelly**

### CODE REVIEW

**Comment by atanisoft** [comment]
This PR is not acceptable, it is a 100% diff of the file and therefore unreviewable.

**Comment by dwightkelly** [comment]
Weird.  I used github upload file to commit. I guess it changed line endings

**Comment by atanisoft** [comment]
That is quite weird. I'm trying to find the option to turn off whitespace diffs so I can find the line(s) you changed. Not seeing it on mobile though so will try desktop shortly.

**Comment by atanisoft** [comment]
Manually merged.

**Pull request closed without merging**
